### ISSUE TITLE
Show the final size of .gif file with custom settings

### ISSUE THREAD

**Issue by hamsternik** [joshdholtz/crunchygif#43]
Hi there! Thanks a lot for that tiny but so functional app. 

I have a feature request described on the title. 
Please @joshdholtz clarify here do you have any plans to work on that app?

**Comment by joshdholtz** [comment]
👋 Hello! Glad you like it 😊 

Are you talking about showing the estimated/final size of the GIF in the settings _before_ the conversion actually happens? 🤔

**Comment by hamsternik** [comment]
> before the conversion actually happens?

You catch my point :) 
I don't know if it's possible but would be great to know what the actual (or expected) size will be after `-> gif` transforming. 

Why is that will be so helpful?

I saw in issues the one about making the gif w/ GitHub appreciate size. So again idk is it possible to calculate / forecast that final size but seems like my current issue is more generic and at the same time preferable as well.

**Comment by joshdholtz** [comment]
I’m actually not sure if this is possible 😔 I use `ffmpeg` under the hood to do the gif creation. I don’t think I have access to command that can predict the size. It also gets a little complex since I’m not just simple breaking the video down into raw frames. I first create a “palette” from the video. This allows for a smaller gif after the conversion since this palette defines only colors the gif needs (as I understand it). So with these steps its actually hard to predict. 

This feature is one that I wanted originally myself when creating the app. I will keep doing some research though to see if it something I can add in 😇
